import{defineConfig}from'vite';import react from'@vitejs/plugin-react';
const names=['Aarav Patel','Diya Shah','Vivaan Mehta','Aanya Trivedi','Reyansh Joshi','Ira Desai','Kabir Dave','Myra Vyas','Arjun Bhatt','Kiara Soni','Dhruv Pandya','Riya Thakkar'];
const units=[{id:'u1',code:'U1',name:'University Road'},{id:'u2',code:'U2',name:'Kalawad Road'},{id:'u3',code:'U3',name:'Raiya Road'}];const programmes=['Todd Care','Playhouse','Pre-K','K1','K2'].map((name,i)=>({id:`p${i+1}`,name,tierName:['Baby Bees','Beginner Bees','Blooming Bees','Growing Bees','Brilliant Bees'][i],colour:['#F4C95D','#74C0D8','#E995B5','#7CCB83','#A890D4'][i]}));
const batches=programmes.map((p,i)=>({id:`b${i+1}`,name:`${p.name} Morning A`,unit:units[i%3],unitId:units[i%3].id,programme:p,programmeId:p.id,shift:'morning',startTime:'09:00',endTime:'12:00',capacity:20,academicYear:'2026-27',isActive:true,_count:{students:6+i}}));
const students=Array.from({length:42},(_,i)=>{const n=names[i%names.length].split(' ');return{id:`s${i+1}`,admissionNo:`BBK-26-${String(i+1).padStart(3,'0')}`,firstName:n[0],lastName:n[1],dateOfBirth:'2021-06-15',gender:i%2?'FEMALE':'MALE',status:'ACTIVE',unit:units[i%3],unitId:units[i%3].id,programme:programmes[i%5],programmeId:programmes[i%5].id,batch:batches[i%5],parentName:`${names[(i+4)%names.length]} Parent`,parentPhone:`98765${String(10000+i).slice(-5)}`,instalmentPlan:'QUARTERLY',createdAt:new Date(2026,5,i%28+1).toISOString()}});
const staff=['Founder','Academic Director','Centre Head','Coordinator','Teacher','Receptionist','HR Manager','Accountant'].map((r,i)=>({id:`e${i+1}`,employeeNo:`EMP-${String(i+1).padStart(3,'0')}`,fullName:names[i],email:`${names[i].toLowerCase().replace(' ','.')}@bumblebkidz.com`,phone:`98250${10000+i}`,role:r.toUpperCase().replaceAll(' ','_'),designation:r,department:i<2?'Head Office':'Education',employmentType:'FULL_TIME',joiningDate:'2024-06-01',status:'ACTIVE',isActive:true,unit:i<2?null:units[i%3],manager:i?{fullName:names[0]}:null,_count:{directReports:i===0?7:0}}));
const leads=Array.from({length:16},(_,i)=>({id:`l${i+1}`,inquiryNo:`INQ-26-${101+i}`,parentName:names[(i+2)%12],childName:names[i%12].split(' ')[0],phone:`99090${10000+i}`,stage:['NEW_INQUIRY','FIRST_BUZZ','EXPERIENCE_SESSION','DISCOVERY_FLIGHT','CONFIRMATION','ENROLLED'][i%6],programmeInterest:programmes[i%5],inquiryChannel:['WALK_IN','WEBSITE','REFERRAL','INSTAGRAM'][i%4],assignedUnit:units[i%3],areaLocality:['University Road','Raiya Circle','Kalawad Road'][i%3],leadScore:42+(i*3)%55,createdAt:new Date(2026,9,i%7+1).toISOString()}));
const funnel=['NEW_INQUIRY','FIRST_BUZZ','EXPERIENCE_SESSION','DISCOVERY_FLIGHT','CONFIRMATION','ENROLLED'].map((stage,i)=>({stage,count:[12,9,7,5,4,31][i]}));const user={id:'preview',email:'founder@bumblebkidz.com',fullName:'Founder Preview',role:'FOUNDER',unitId:null,unitName:'Head Office'};
function api(){return{name:'demo-api',configureServer(s:any){s.middlewares.use('/api',(q:any,r:any)=>{r.setHeader('Content-Type','application/json');const u=q.url.split('?')[0];let v:any=[];if(u==='/auth/login')v={accessToken:'preview',refreshToken:'preview',user};else if(u==='/auth/me')v=user;else if(u==='/theme/default')v={value:null};else if(u==='/units')v=units;else if(u==='/programmes')v=programmes;else if(u==='/batches')v=batches;else if(u==='/students'||u==='/admissions')v=students;else if(u==='/users'||u==='/hr/employees')v=staff;else if(u==='/leads')v=leads;else if(u==='/dashboard/summary')v={students:42,batches:8,leadsOpen:37,attendance:{present:39,total:42},fees:{collected:1845000,receipts:52},funnel,programmeDistribution:programmes.map((p,i)=>({...p,count:7+i})),recentLeads:leads.slice(0,5)};else if(u==='/attendance/summary')v={present:39,absent:2,leave:1,total:42};else if(u==='/fees/summary')v={collected:1845000,outstanding:405000,collectionRate:82};else if(u==='/areas')v=[{id:'a1',locality:'University Road',pincode:'360005',suggestedUnit:units[0],isActive:true},{id:'a2',locality:'Raiya Circle',pincode:'360007',suggestedUnit:units[2],isActive:true}];r.end(JSON.stringify(v))})}}}export default defineConfig({plugins:[react(),api()],server:{host:'0.0.0.0',port:5173,allowedHosts:true}})
