import { BadRequestException, Body, Controller, Get, Module, NotFoundException, Param, Patch, Post, Query, Req, UseGuards, UploadedFile, UseInterceptors } from '@nestjs/common';
import { AuthGuard, HO_ROLES, Roles } from '../auth/auth';
import { PrismaService } from '../prisma.service';
import { AuditService } from './admin.controller';
import { FileInterceptor } from '@nestjs/platform-express';
import * as XLSX from 'xlsx';

const HR_ROLES = ['FOUNDER', 'HR_MANAGER'];
const TYPES = ['MORNING_SALARIED', 'EVENING_HOURLY', 'DUAL'];
const STATUSES = ['ACTIVE', 'ON_NOTICE', 'RELIEVED', 'SUSPENDED'];
@Controller('hr') @UseGuards(AuthGuard) @Roles(...HR_ROLES)
export class HrController {
  constructor(private prisma: PrismaService, private audit: AuditService) {}






  @Get('statutory') statutory(){return this.prisma.statutoryScheme.findMany({include:{slabs:true},orderBy:[{code:'asc'},{effectiveFrom:'desc'}]})}
  @Post('statutory') async statutoryMaster(@Req()req:any,@Body()b:any){if(!['PF','ESIC','PT'].includes(b.code)||!b.effectiveFrom)throw new BadRequestException('PF/ESIC/PT and effective date required');const r=await this.prisma.statutoryScheme.create({data:{code:b.code,name:b.name||b.code,effectiveFrom:new Date(b.effectiveFrom),effectiveTo:b.effectiveTo?new Date(b.effectiveTo):null,employeeRate:Number(b.employeeRate||0),employerRate:Number(b.employerRate||0),wageCeiling:b.wageCeiling?Number(b.wageCeiling):null,calculationBasis:b.calculationBasis||'GROSS',slabs:{create:(b.slabs||[]).map((x:any)=>({minAmount:Number(x.minAmount),maxAmount:x.maxAmount?Number(x.maxAmount):null,deduction:Number(x.deduction)}))}}});await this.audit.log(req,'statutory_schemes',r.id,'INSERT',null,r);return r}
  @Post('payroll/:id/apply-statutory') async applyStatutory(@Req()req:any,@Param('id')id:string){const run=await this.prisma.payrollRun.findUnique({where:{id},include:{lines:{include:{employee:true}}}});if(!run||run.status!=='DRAFT')throw new BadRequestException('Draft payroll run required');const date=new Date(`${run.month}-01`),schemes=await this.prisma.statutoryScheme.findMany({where:{active:true,effectiveFrom:{lte:date},OR:[{effectiveTo:null},{effectiveTo:{gte:date}}]},include:{slabs:true}});for(const l of run.lines){let employeeDed=0,employer=0;const applied:any={};for(const s of schemes){if(!(l.employee as any)[`${s.code.toLowerCase()}Enabled`])continue;const basis=Math.min(Number(l.gross),s.wageCeiling?Number(s.wageCeiling):Number(l.gross));let deduction=s.code==='PT'?(s.slabs.find((x:any)=>basis>=Number(x.minAmount)&&(!x.maxAmount||basis<=Number(x.maxAmount)))?.deduction||0):basis*Number(s.employeeRate)/100;const er=basis*Number(s.employerRate)/100;employeeDed+=Number(deduction);employer+=er;applied[s.code]={basis,deduction:Number(deduction),employer:er}}await this.prisma.payrollLine.update({where:{id:l.id},data:{deductions:{increment:employeeDed},employerContributions:employer,net:{decrement:employeeDed},details:{...(l.details as any),statutory:applied}}})}await this.audit.log(req,'payroll_runs',id,'UPDATE',null,{statutoryApplied:true});return this.prisma.payrollRun.findUnique({where:{id},include:{lines:true}})}

  @Post('employees/:id/minute-rate') async minuteRate(@Req()req:any,@Param('id')employeeId:string,@Body()b:any){if(Number(b.rate)<=0||!b.effectiveFrom)throw new BadRequestException('Positive rate and effective date required');const r=await this.prisma.employeeMinuteRate.create({data:{employeeId,rate:Number(b.rate),effectiveFrom:new Date(b.effectiveFrom),effectiveTo:b.effectiveTo?new Date(b.effectiveTo):null}});await this.audit.log(req,'employee_minute_rates',r.id,'INSERT',null,r);return r}
  @Post('payroll/evening/calculate') async eveningPayroll(@Req()req:any,@Body()b:any){const month=b.month;if(!/^\d{4}-\d{2}$/.test(month))throw new BadRequestException('Month must be YYYY-MM');const[y,m]=month.split('-').map(Number),from=new Date(`${month}-01`),to=new Date(y,m,1);const employees=await this.prisma.employee.findMany({where:{status:'ACTIVE',employmentType:{in:['EVENING_HOURLY','DUAL']},...(b.unitId?{unitId:b.unitId}:{})}});const run=await this.prisma.payrollRun.create({data:{type:'EVENING',month,unitId:b.unitId||null,createdById:req.user.sub}});for(const e of employees){const rate=await this.prisma.employeeMinuteRate.findFirst({where:{employeeId:e.id,effectiveFrom:{lte:new Date(y,m-1,new Date(y,m,0).getDate())},OR:[{effectiveTo:null},{effectiveTo:{gte:from}}]},orderBy:{effectiveFrom:'desc'}});if(!rate)continue;const att=await this.prisma.staffAttendance.findMany({where:{employeeId:e.id,date:{gte:from,lt:to}}});if(att.some((a:any)=>a.exception&&!a.exceptionResolved))continue;const worked=att.reduce((n:number,a:any)=>n+a.workedMinutes,0);const ot=await this.prisma.overtimeAuthorisation.findMany({where:{employeeId:e.id,status:'APPROVED',date:{gte:from,lt:to}}});const otPay=ot.reduce((n:number,x:any)=>n+(x.eligibleMinutes||0)*Number(rate.rate)*Number(x.multiplier),0),gross=worked*Number(rate.rate)+otPay;await this.prisma.payrollLine.create({data:{runId:run.id,employeeId:e.id,gross,deductions:0,net:gross,workedMinutes:worked,otMinutes:ot.reduce((n:number,x:any)=>n+(x.eligibleMinutes||0),0),details:{minuteRate:Number(rate.rate),regularPay:worked*Number(rate.rate),otPay}}})}return this.prisma.payrollRun.findUnique({where:{id:run.id},include:{lines:{include:{employee:true}}}})}

  @Post('payroll/morning/calculate') async morningPayroll(@Req()req:any,@Body()b:any){const month=b.month;if(!/^\d{4}-\d{2}$/.test(month))throw new BadRequestException('Month must be YYYY-MM');const [y,m]=month.split('-').map(Number),days=new Date(y,m,0).getDate(),from=new Date(`${month}-01`),to=new Date(y,m,1);const employees=await this.prisma.employee.findMany({where:{status:'ACTIVE',employmentType:{in:['MORNING_SALARIED','DUAL']},...(b.unitId?{unitId:b.unitId}:{})}});const run=await this.prisma.payrollRun.create({data:{type:'MORNING',month,unitId:b.unitId||null,createdById:req.user.sub}});for(const e of employees){const comps=await this.prisma.employeeSalaryComponent.findMany({where:{employeeId:e.id,effectiveFrom:{lte:new Date(y,m-1,days)},OR:[{effectiveTo:null},{effectiveTo:{gte:from}}]},include:{component:true}});const earnings=comps.filter((x:any)=>x.component.type==='EARNING').reduce((n:number,x:any)=>n+Number(x.value),0),fixedDed=comps.filter((x:any)=>x.component.type==='DEDUCTION').reduce((n:number,x:any)=>n+Number(x.value),0);const att=await this.prisma.staffAttendance.findMany({where:{employeeId:e.id,date:{gte:from,lt:to}}});if(att.some((a:any)=>a.exception&&!a.exceptionResolved))continue;const leaves=await this.prisma.staffLeave.findMany({where:{employeeId:e.id,status:'APPROVED',isLwp:true,fromDate:{lt:to},toDate:{gte:from}}});const lwp=leaves.reduce((n:number,x:any)=>n+Number(x.days),0),perDay=earnings/days;const late=att.filter((a:any)=>a.lateMinutes>0).sort((a:any,b:any)=>a.date-b.date);let lateDed=0;late.slice(2).forEach((a:any)=>{if(a.lateMinutes<=30)lateDed+=earnings*.0035;else if(a.lateMinutes<=60)lateDed+=perDay/24;else if(a.lateMinutes<=120)lateDed+=perDay/12;else lateDed+=perDay/6});const ot=await this.prisma.overtimeAuthorisation.findMany({where:{employeeId:e.id,status:'APPROVED',date:{gte:from,lt:to}}});const minuteRate=earnings/days/((att.length&&att.reduce((n:number,a:any)=>n+a.workedMinutes,0)/att.length)||420),otPay=ot.reduce((n:number,x:any)=>n+(x.eligibleMinutes||0)*minuteRate*Number(x.multiplier),0);const adjustments=await this.prisma.payrollAdjustment.findMany({where:{employeeId:e.id,month,status:'APPROVED'}});const adj=adjustments.reduce((n:number,x:any)=>n+(x.type==='EARNING'?1:-1)*Number(x.amount),0),ded=fixedDed+lwp*perDay+lateDed,gross=earnings+otPay+Math.max(0,adj),net=gross-ded+Math.min(0,adj);await this.prisma.payrollLine.create({data:{runId:run.id,employeeId:e.id,gross,deductions:ded,net,workedMinutes:att.reduce((n:number,a:any)=>n+a.workedMinutes,0),otMinutes:ot.reduce((n:number,x:any)=>n+(x.eligibleMinutes||0),0),lwpDays:lwp,details:{calendarDays:days,baseEarnings:earnings,fixedDeduction:fixedDed,lwpDeduction:lwp*perDay,lateDeduction:lateDed,otPay,adjustment:adj}}})}return this.prisma.payrollRun.findUnique({where:{id:run.id},include:{lines:{include:{employee:true}}}})}
  @Get('payroll/runs') runs(){return this.prisma.payrollRun.findMany({include:{lines:{include:{employee:{select:{employeeNo:true,fullName:true}}}}},orderBy:{createdAt:'desc'}})}

  @Get('overtime') overtime(){return this.prisma.overtimeAuthorisation.findMany({include:{employee:{select:{employeeNo:true,fullName:true}}},orderBy:{date:'desc'}})}
  @Post('overtime') async requestOt(@Body()b:any){if(!b.employeeId||!b.date||!b.expectedMinutes||!b.reason||Number(b.multiplier)<=0)throw new BadRequestException('Complete OT request required');return this.prisma.overtimeAuthorisation.create({data:{employeeId:b.employeeId,date:new Date(b.date),expectedMinutes:Number(b.expectedMinutes),reason:b.reason,multiplier:Number(b.multiplier)}})}
  @Patch('overtime/:id/approve') async approveOt(@Req()req:any,@Param('id')id:string,@Body()b:any){const old=await this.prisma.overtimeAuthorisation.findUnique({where:{id}});if(!old)throw new NotFoundException();const att=await this.prisma.staffAttendance.findUnique({where:{employeeId_date:{employeeId:old.employeeId,date:old.date}}});const actual=att?Math.max(0,att.workedMinutes-((await this.prisma.employeeShift.findFirst({where:{employeeId:old.employeeId,effectiveFrom:{lte:old.date},OR:[{effectiveTo:null},{effectiveTo:{gte:old.date}}]},include:{shift:true},orderBy:{effectiveFrom:'desc'}}))?.shift.workingMinutes||0)):0;const r=await this.prisma.overtimeAuthorisation.update({where:{id},data:{status:b.approved?'APPROVED':'REJECTED',approvedById:req.user.sub,approvedAt:new Date(),actualMinutes:actual,eligibleMinutes:b.approved?Math.min(actual,old.expectedMinutes):0}});await this.audit.log(req,'overtime_authorisations',id,'UPDATE',old,r);return r}

  @Get('leave/policies') policies(){return this.prisma.leavePolicy.findMany({orderBy:[{year:'desc'},{leaveType:'asc'}]})}
  @Post('leave/policies') async policy(@Req()req:any,@Body()b:any){if(!b.year||!['CL','SL','PL'].includes(b.leaveType))throw new BadRequestException('Year and CL/SL/PL required');const r=await this.prisma.leavePolicy.upsert({where:{year_leaveType:{year:Number(b.year),leaveType:b.leaveType}},create:{year:Number(b.year),leaveType:b.leaveType,allocation:Number(b.allocation),carryForwardCap:Number(b.carryForwardCap),effectiveFrom:new Date(b.effectiveFrom||`${b.year}-01-01`)},update:{allocation:Number(b.allocation),carryForwardCap:Number(b.carryForwardCap),effectiveFrom:new Date(b.effectiveFrom||`${b.year}-01-01`)}});await this.audit.log(req,'leave_policies',r.id,'UPDATE',null,r);return r}
  @Post('leave/apply') async applyLeave(@Body()b:any){if(!b.employeeId||!b.fromDate||!b.toDate||!b.reason)throw new BadRequestException('Complete leave request required');const from=new Date(b.fromDate),to=new Date(b.toDate),days=Math.floor((+to-+from)/86400000)+1;if(days<1)throw new BadRequestException('Invalid dates');return this.prisma.staffLeave.create({data:{employeeId:b.employeeId,leaveType:b.leaveType,fromDate:from,toDate:to,days,reason:b.reason}})}
  @Get('leave') leaves(){return this.prisma.staffLeave.findMany({include:{employee:{select:{employeeNo:true,fullName:true}}},orderBy:{createdAt:'desc'}})}
  @Patch('leave/:id/approve') async approveLeave(@Req()req:any,@Param('id')id:string,@Body()b:any){const old=await this.prisma.staffLeave.findUnique({where:{id}});if(!old)throw new NotFoundException();const status=b.approved?'APPROVED':'REJECTED';const r=await this.prisma.staffLeave.update({where:{id},data:{status,hrApprovedById:req.user.sub,isLwp:!!b.isLwp}});if(b.approved&&!b.isLwp)await this.prisma.leaveBalance.upsert({where:{employeeId_year_leaveType:{employeeId:r.employeeId,year:r.fromDate.getFullYear(),leaveType:r.leaveType}},create:{employeeId:r.employeeId,year:r.fromDate.getFullYear(),leaveType:r.leaveType,used:r.days},update:{used:{increment:r.days}}});await this.audit.log(req,'staff_leaves',id,'UPDATE',old,r);return r}

  @Post('attendance/import') @UseInterceptors(FileInterceptor('file')) async importAttendance(@Req()req:any,@UploadedFile()file:Express.Multer.File){if(!file)throw new BadRequestException('CSV or Excel file required');let rows:any[]=[];try{const wb=XLSX.read(file.buffer,{type:'buffer',cellDates:true});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]])}catch{throw new BadRequestException('Unable to parse attendance file')}const batch=await this.prisma.attendanceImport.create({data:{fileName:file.originalname,source:/csv/i.test(file.originalname)?'CSV':'BIOMETRIC_EXCEL',totalRows:rows.length,importedById:req.user.sub}});let errors=0;for(const x of rows){const employeeNo=String(x.employeeNo||x['Employee No']||x.code||'').trim();const employee=await this.prisma.employee.findUnique({where:{employeeNo}});if(!employee){errors++;continue}const date=new Date(x.date||x.Date);const first=x.firstIn||x['First In'];const last=x.lastOut||x['Last Out'];const round=(d:any)=>{const v=new Date(`${date.toISOString().slice(0,10)}T${d}`);v.setMinutes(Math.round(v.getMinutes()/5)*5,0,0);return v};const firstIn=first?round(first):null,lastOut=last?round(last):null;const exception=!firstIn||!lastOut?'MISSING_PUNCH':lastOut<=firstIn?'INVALID_PUNCH_ORDER':null;const worked=firstIn&&lastOut&&!exception?Math.max(0,Math.round((+lastOut-+firstIn)/60000)):0;await this.prisma.staffAttendance.upsert({where:{employeeId_date:{employeeId:employee.id,date}},create:{employeeId:employee.id,date,firstIn,lastOut,workedMinutes:worked,status:exception?'EXCEPTION':'PRESENT',exception,importId:batch.id},update:{firstIn,lastOut,workedMinutes:worked,status:exception?'EXCEPTION':'PRESENT',exception,exceptionResolved:false,importId:batch.id}})}await this.prisma.attendanceImport.update({where:{id:batch.id},data:{errorRows:errors}});return{...batch,errorRows:errors}}
  @Get('attendance') attendance(@Query('month')month?:string){const m=month||new Date().toISOString().slice(0,7),from=new Date(`${m}-01`),to=new Date(from);to.setMonth(to.getMonth()+1);return this.prisma.staffAttendance.findMany({where:{date:{gte:from,lt:to}},include:{employee:{select:{employeeNo:true,fullName:true}}},orderBy:[{date:'desc'}]})}
  @Patch('attendance/:id/resolve') async resolveAttendance(@Req()req:any,@Param('id')id:string,@Body()b:any){if(!b.reason?.trim())throw new BadRequestException('Correction reason required');const old=await this.prisma.staffAttendance.findUnique({where:{id}});if(!old)throw new NotFoundException();const firstIn=b.firstIn?new Date(b.firstIn):old.firstIn,lastOut=b.lastOut?new Date(b.lastOut):old.lastOut;const worked=firstIn&&lastOut?Math.max(0,Math.round((+lastOut-+firstIn)/60000)):0;const r=await this.prisma.staffAttendance.update({where:{id},data:{firstIn,lastOut,workedMinutes:worked,exception:null,exceptionResolved:true,status:'PRESENT',correctionReason:b.reason}});await this.audit.log(req,'staff_attendance',id,'UPDATE',old,r);return r}

  @Get('masters') async masters(){const [shifts,holidays,components]=await Promise.all([this.prisma.hrShift.findMany({orderBy:{name:'asc'}}),this.prisma.hrHoliday.findMany({orderBy:{date:'desc'}}),this.prisma.salaryComponent.findMany({orderBy:{name:'asc'}})]);return {shifts,holidays,components}}
  @Post('shifts') async shift(@Req()req:any,@Body()b:any){if(!b.name||!b.code||!b.startTime||!b.endTime||!b.workingMinutes||!b.halfDayMinutes)throw new BadRequestException('Complete shift rules required');const r=await this.prisma.hrShift.create({data:{name:b.name,code:b.code,startTime:b.startTime,endTime:b.endTime,workingMinutes:Number(b.workingMinutes),halfDayMinutes:Number(b.halfDayMinutes),otTriggerTime:b.otTriggerTime||null}});await this.audit.log(req,'hr_shifts',r.id,'INSERT',null,r);return r}
  @Post('holidays') async holiday(@Req()req:any,@Body()b:any){if(!b.date||!b.name)throw new BadRequestException('Date and name required');const r=await this.prisma.hrHoliday.create({data:{unitId:b.unitId||null,date:new Date(b.date),name:b.name,paid:b.paid!==false}});await this.audit.log(req,'hr_holidays',r.id,'INSERT',null,r);return r}
  @Post('salary-components') async component(@Req()req:any,@Body()b:any){if(!b.code||!b.name||!['EARNING','DEDUCTION'].includes(b.type)||!['FIXED','PERCENTAGE'].includes(b.calculationType))throw new BadRequestException('Invalid component');const r=await this.prisma.salaryComponent.create({data:{code:b.code,name:b.name,type:b.type,calculationType:b.calculationType,defaultValue:Number(b.defaultValue||0),pfApplicable:!!b.pfApplicable,esicApplicable:!!b.esicApplicable,ptApplicable:!!b.ptApplicable}});await this.audit.log(req,'salary_components',r.id,'INSERT',null,r);return r}
  @Post('employees/:id/shift') async assignShift(@Req()req:any,@Param('id')employeeId:string,@Body()b:any){if(!b.shiftId||!b.effectiveFrom)throw new BadRequestException('Shift and effective date required');const r=await this.prisma.employeeShift.create({data:{employeeId,shiftId:b.shiftId,effectiveFrom:new Date(b.effectiveFrom),effectiveTo:b.effectiveTo?new Date(b.effectiveTo):null}});await this.audit.log(req,'employee_shifts',r.id,'INSERT',null,r);return r}
  @Post('employees/:id/compensation') async compensation(@Req()req:any,@Param('id')employeeId:string,@Body()b:any){if(!b.componentId||!b.effectiveFrom)throw new BadRequestException('Component and effective date required');const r=await this.prisma.employeeSalaryComponent.create({data:{employeeId,componentId:b.componentId,value:Number(b.value),effectiveFrom:new Date(b.effectiveFrom),effectiveTo:b.effectiveTo?new Date(b.effectiveTo):null}});await this.audit.log(req,'employee_salary_components',r.id,'INSERT',null,r);return r}

  @Get('employees')
  employees(@Req() req:any,@Query('unitId') unitId?:string,@Query('status') status?:string) {
    const scope=HO_ROLES.includes(req.user.role)||req.user.role==='HR_MANAGER'?(unitId?{unitId}:{}):{unitId:req.user.unitId};
    return this.prisma.employee.findMany({where:{...scope,...(status?{status}:{})},include:{manager:{select:{id:true,employeeNo:true,fullName:true}},_count:{select:{directReports:true}},history:{orderBy:{effectiveFrom:'desc'},take:1}},orderBy:{fullName:'asc'}});
  }
  @Get('employees/:id') async one(@Param('id') id:string) {
    const row=await this.prisma.employee.findUnique({where:{id},include:{manager:true,directReports:{select:{id:true,employeeNo:true,fullName:true,designation:true}},history:{orderBy:{effectiveFrom:'desc'}}}}); if(!row)throw new NotFoundException(); return row;
  }
  @Post('employees') async create(@Req() req:any,@Body() b:any) {
    if(!b.fullName?.trim()||!b.unitId||!b.designation?.trim()||!b.joiningDate||!TYPES.includes(b.employmentType))throw new BadRequestException('Name, unit, designation, joining date and employment type are required');
    const unit=await this.prisma.unit.findUnique({where:{id:b.unitId}});if(!unit)throw new BadRequestException('Invalid unit');
    if(b.reportingManagerId===b.id)throw new BadRequestException('Employee cannot report to self');
    const year=new Date(b.joiningDate).getFullYear().toString().slice(-2);const count=await this.prisma.employee.count();const employeeNo=`BB-${unit.code}-EMP-${year}-${String(count+1).padStart(4,'0')}`;
    const data={employeeNo,fullName:b.fullName.trim(),email:b.email?.trim()||null,phone:b.phone?.trim()||null,dateOfBirth:b.dateOfBirth?new Date(b.dateOfBirth):null,joiningDate:new Date(b.joiningDate),unitId:b.unitId,department:b.department||null,designation:b.designation.trim(),reportingManagerId:b.reportingManagerId||null,employmentType:b.employmentType,bankAccountName:b.bankAccountName||null,bankAccountNo:b.bankAccountNo||null,bankIfsc:b.bankIfsc||null,pan:b.pan||null,uan:b.uan||null,esicNumber:b.esicNumber||null,pfEnabled:!!b.pfEnabled,esicEnabled:!!b.esicEnabled,ptEnabled:!!b.ptEnabled};
    const row=await this.prisma.$transaction(async(tx:any)=>{const e=await tx.employee.create({data});await tx.employmentHistory.create({data:{employeeId:e.id,effectiveFrom:new Date(b.joiningDate),unitId:b.unitId,department:b.department||null,designation:b.designation.trim(),employmentType:b.employmentType,reportingManagerId:b.reportingManagerId||null,reason:'Initial employment',changedById:req.user.sub}});return e});await this.audit.log(req,'employees',row.id,'INSERT',null,{...row,bankAccountNo:row.bankAccountNo?'***':null,pan:row.pan?'***':null});return row;
  }
  @Patch('employees/:id/employment') async change(@Req() req:any,@Param('id') id:string,@Body() b:any) {
    const old=await this.prisma.employee.findUnique({where:{id}});if(!old)throw new NotFoundException();if(b.reportingManagerId===id)throw new BadRequestException('Employee cannot report to self');if(b.employmentType&&!TYPES.includes(b.employmentType))throw new BadRequestException('Invalid employment type');if(b.status&&!STATUSES.includes(b.status))throw new BadRequestException('Invalid status');
    const effectiveFrom=new Date(b.effectiveFrom||new Date());const next={unitId:b.unitId||old.unitId,department:b.department===undefined?old.department:b.department,designation:b.designation||old.designation,employmentType:b.employmentType||old.employmentType,reportingManagerId:b.reportingManagerId===undefined?old.reportingManagerId:(b.reportingManagerId||null)};
    const row=await this.prisma.$transaction(async(tx:any)=>{await tx.employmentHistory.updateMany({where:{employeeId:id,effectiveTo:null},data:{effectiveTo:new Date(effectiveFrom.getTime()-86400000)}});await tx.employmentHistory.create({data:{employeeId:id,effectiveFrom,...next,reason:b.reason||'Employment change',changedById:req.user.sub}});return tx.employee.update({where:{id},data:{...next,status:b.status||old.status,relievingDate:b.relievingDate?new Date(b.relievingDate):old.relievingDate}})});await this.audit.log(req,'employees',id,'UPDATE',old,row);return row;
  }
}
@Module({controllers:[HrController],providers:[PrismaService,AuditService]}) export class HrModule {}
