import { BadRequestException, Body, Controller, Get, Module, NotFoundException, Param, Patch, Post, Query, Req, UseGuards, UploadedFile, UseInterceptors } from '@nestjs/common';
import { AuthGuard, HO_ROLES, Roles } from '../auth/auth';
import { PrismaService } from '../prisma.service';
import { AuditService } from './admin.controller';
import { FileInterceptor } from '@nestjs/platform-express';
import * as XLSX from 'xlsx';

const HR_ROLES = ['FOUNDER', 'HR_MANAGER'];
const TYPES = ['MORNING_SALARIED', 'EVENING_HOURLY', 'DUAL'];
const STATUSES = ['ACTIVE', 'ON_NOTICE', 'RELIEVED', 'SUSPENDED'];
@Controller('hr') @UseGuards(AuthGuard) @Roles(...HR_ROLES)
export class HrController {
  constructor(private prisma: PrismaService, private audit: AuditService) {}

  @Post('attendance/import') @UseInterceptors(FileInterceptor('file')) async importAttendance(@Req()req:any,@UploadedFile()file:Express.Multer.File){if(!file)throw new BadRequestException('CSV or Excel file required');let rows:any[]=[];try{const wb=XLSX.read(file.buffer,{type:'buffer',cellDates:true});rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]])}catch{throw new BadRequestException('Unable to parse attendance file')}const batch=await this.prisma.attendanceImport.create({data:{fileName:file.originalname,source:/csv/i.test(file.originalname)?'CSV':'BIOMETRIC_EXCEL',totalRows:rows.length,importedById:req.user.sub}});let errors=0;for(const x of rows){const employeeNo=String(x.employeeNo||x['Employee No']||x.code||'').trim();const employee=await this.prisma.employee.findUnique({where:{employeeNo}});if(!employee){errors++;continue}const date=new Date(x.date||x.Date);const first=x.firstIn||x['First In'];const last=x.lastOut||x['Last Out'];const round=(d:any)=>{const v=new Date(`${date.toISOString().slice(0,10)}T${d}`);v.setMinutes(Math.round(v.getMinutes()/5)*5,0,0);return v};const firstIn=first?round(first):null,lastOut=last?round(last):null;const exception=!firstIn||!lastOut?'MISSING_PUNCH':lastOut<=firstIn?'INVALID_PUNCH_ORDER':null;const worked=firstIn&&lastOut&&!exception?Math.max(0,Math.round((+lastOut-+firstIn)/60000)):0;await this.prisma.staffAttendance.upsert({where:{employeeId_date:{employeeId:employee.id,date}},create:{employeeId:employee.id,date,firstIn,lastOut,workedMinutes:worked,status:exception?'EXCEPTION':'PRESENT',exception,importId:batch.id},update:{firstIn,lastOut,workedMinutes:worked,status:exception?'EXCEPTION':'PRESENT',exception,exceptionResolved:false,importId:batch.id}})}await this.prisma.attendanceImport.update({where:{id:batch.id},data:{errorRows:errors}});return{...batch,errorRows:errors}}
  @Get('attendance') attendance(@Query('month')month?:string){const m=month||new Date().toISOString().slice(0,7),from=new Date(`${m}-01`),to=new Date(from);to.setMonth(to.getMonth()+1);return this.prisma.staffAttendance.findMany({where:{date:{gte:from,lt:to}},include:{employee:{select:{employeeNo:true,fullName:true}}},orderBy:[{date:'desc'}]})}
  @Patch('attendance/:id/resolve') async resolveAttendance(@Req()req:any,@Param('id')id:string,@Body()b:any){if(!b.reason?.trim())throw new BadRequestException('Correction reason required');const old=await this.prisma.staffAttendance.findUnique({where:{id}});if(!old)throw new NotFoundException();const firstIn=b.firstIn?new Date(b.firstIn):old.firstIn,lastOut=b.lastOut?new Date(b.lastOut):old.lastOut;const worked=firstIn&&lastOut?Math.max(0,Math.round((+lastOut-+firstIn)/60000)):0;const r=await this.prisma.staffAttendance.update({where:{id},data:{firstIn,lastOut,workedMinutes:worked,exception:null,exceptionResolved:true,status:'PRESENT',correctionReason:b.reason}});await this.audit.log(req,'staff_attendance',id,'UPDATE',old,r);return r}

  @Get('masters') async masters(){const [shifts,holidays,components]=await Promise.all([this.prisma.hrShift.findMany({orderBy:{name:'asc'}}),this.prisma.hrHoliday.findMany({orderBy:{date:'desc'}}),this.prisma.salaryComponent.findMany({orderBy:{name:'asc'}})]);return {shifts,holidays,components}}
  @Post('shifts') async shift(@Req()req:any,@Body()b:any){if(!b.name||!b.code||!b.startTime||!b.endTime||!b.workingMinutes||!b.halfDayMinutes)throw new BadRequestException('Complete shift rules required');const r=await this.prisma.hrShift.create({data:{name:b.name,code:b.code,startTime:b.startTime,endTime:b.endTime,workingMinutes:Number(b.workingMinutes),halfDayMinutes:Number(b.halfDayMinutes),otTriggerTime:b.otTriggerTime||null}});await this.audit.log(req,'hr_shifts',r.id,'INSERT',null,r);return r}
  @Post('holidays') async holiday(@Req()req:any,@Body()b:any){if(!b.date||!b.name)throw new BadRequestException('Date and name required');const r=await this.prisma.hrHoliday.create({data:{unitId:b.unitId||null,date:new Date(b.date),name:b.name,paid:b.paid!==false}});await this.audit.log(req,'hr_holidays',r.id,'INSERT',null,r);return r}
  @Post('salary-components') async component(@Req()req:any,@Body()b:any){if(!b.code||!b.name||!['EARNING','DEDUCTION'].includes(b.type)||!['FIXED','PERCENTAGE'].includes(b.calculationType))throw new BadRequestException('Invalid component');const r=await this.prisma.salaryComponent.create({data:{code:b.code,name:b.name,type:b.type,calculationType:b.calculationType,defaultValue:Number(b.defaultValue||0),pfApplicable:!!b.pfApplicable,esicApplicable:!!b.esicApplicable,ptApplicable:!!b.ptApplicable}});await this.audit.log(req,'salary_components',r.id,'INSERT',null,r);return r}
  @Post('employees/:id/shift') async assignShift(@Req()req:any,@Param('id')employeeId:string,@Body()b:any){if(!b.shiftId||!b.effectiveFrom)throw new BadRequestException('Shift and effective date required');const r=await this.prisma.employeeShift.create({data:{employeeId,shiftId:b.shiftId,effectiveFrom:new Date(b.effectiveFrom),effectiveTo:b.effectiveTo?new Date(b.effectiveTo):null}});await this.audit.log(req,'employee_shifts',r.id,'INSERT',null,r);return r}
  @Post('employees/:id/compensation') async compensation(@Req()req:any,@Param('id')employeeId:string,@Body()b:any){if(!b.componentId||!b.effectiveFrom)throw new BadRequestException('Component and effective date required');const r=await this.prisma.employeeSalaryComponent.create({data:{employeeId,componentId:b.componentId,value:Number(b.value),effectiveFrom:new Date(b.effectiveFrom),effectiveTo:b.effectiveTo?new Date(b.effectiveTo):null}});await this.audit.log(req,'employee_salary_components',r.id,'INSERT',null,r);return r}

  @Get('employees')
  employees(@Req() req:any,@Query('unitId') unitId?:string,@Query('status') status?:string) {
    const scope=HO_ROLES.includes(req.user.role)||req.user.role==='HR_MANAGER'?(unitId?{unitId}:{}):{unitId:req.user.unitId};
    return this.prisma.employee.findMany({where:{...scope,...(status?{status}:{})},include:{manager:{select:{id:true,employeeNo:true,fullName:true}},_count:{select:{directReports:true}},history:{orderBy:{effectiveFrom:'desc'},take:1}},orderBy:{fullName:'asc'}});
  }
  @Get('employees/:id') async one(@Param('id') id:string) {
    const row=await this.prisma.employee.findUnique({where:{id},include:{manager:true,directReports:{select:{id:true,employeeNo:true,fullName:true,designation:true}},history:{orderBy:{effectiveFrom:'desc'}}}}); if(!row)throw new NotFoundException(); return row;
  }
  @Post('employees') async create(@Req() req:any,@Body() b:any) {
    if(!b.fullName?.trim()||!b.unitId||!b.designation?.trim()||!b.joiningDate||!TYPES.includes(b.employmentType))throw new BadRequestException('Name, unit, designation, joining date and employment type are required');
    const unit=await this.prisma.unit.findUnique({where:{id:b.unitId}});if(!unit)throw new BadRequestException('Invalid unit');
    if(b.reportingManagerId===b.id)throw new BadRequestException('Employee cannot report to self');
    const year=new Date(b.joiningDate).getFullYear().toString().slice(-2);const count=await this.prisma.employee.count();const employeeNo=`BB-${unit.code}-EMP-${year}-${String(count+1).padStart(4,'0')}`;
    const data={employeeNo,fullName:b.fullName.trim(),email:b.email?.trim()||null,phone:b.phone?.trim()||null,dateOfBirth:b.dateOfBirth?new Date(b.dateOfBirth):null,joiningDate:new Date(b.joiningDate),unitId:b.unitId,department:b.department||null,designation:b.designation.trim(),reportingManagerId:b.reportingManagerId||null,employmentType:b.employmentType,bankAccountName:b.bankAccountName||null,bankAccountNo:b.bankAccountNo||null,bankIfsc:b.bankIfsc||null,pan:b.pan||null,uan:b.uan||null,esicNumber:b.esicNumber||null,pfEnabled:!!b.pfEnabled,esicEnabled:!!b.esicEnabled,ptEnabled:!!b.ptEnabled};
    const row=await this.prisma.$transaction(async(tx:any)=>{const e=await tx.employee.create({data});await tx.employmentHistory.create({data:{employeeId:e.id,effectiveFrom:new Date(b.joiningDate),unitId:b.unitId,department:b.department||null,designation:b.designation.trim(),employmentType:b.employmentType,reportingManagerId:b.reportingManagerId||null,reason:'Initial employment',changedById:req.user.sub}});return e});await this.audit.log(req,'employees',row.id,'INSERT',null,{...row,bankAccountNo:row.bankAccountNo?'***':null,pan:row.pan?'***':null});return row;
  }
  @Patch('employees/:id/employment') async change(@Req() req:any,@Param('id') id:string,@Body() b:any) {
    const old=await this.prisma.employee.findUnique({where:{id}});if(!old)throw new NotFoundException();if(b.reportingManagerId===id)throw new BadRequestException('Employee cannot report to self');if(b.employmentType&&!TYPES.includes(b.employmentType))throw new BadRequestException('Invalid employment type');if(b.status&&!STATUSES.includes(b.status))throw new BadRequestException('Invalid status');
    const effectiveFrom=new Date(b.effectiveFrom||new Date());const next={unitId:b.unitId||old.unitId,department:b.department===undefined?old.department:b.department,designation:b.designation||old.designation,employmentType:b.employmentType||old.employmentType,reportingManagerId:b.reportingManagerId===undefined?old.reportingManagerId:(b.reportingManagerId||null)};
    const row=await this.prisma.$transaction(async(tx:any)=>{await tx.employmentHistory.updateMany({where:{employeeId:id,effectiveTo:null},data:{effectiveTo:new Date(effectiveFrom.getTime()-86400000)}});await tx.employmentHistory.create({data:{employeeId:id,effectiveFrom,...next,reason:b.reason||'Employment change',changedById:req.user.sub}});return tx.employee.update({where:{id},data:{...next,status:b.status||old.status,relievingDate:b.relievingDate?new Date(b.relievingDate):old.relievingDate}})});await this.audit.log(req,'employees',id,'UPDATE',old,row);return row;
  }
}
@Module({controllers:[HrController],providers:[PrismaService,AuditService]}) export class HrModule {}
