import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Activity, Boxes, IndianRupee, TrendingUp, Users, WalletCards } from 'lucide-react';
import { api } from '../lib/api';
import { PageHeader } from '../components/layout/AppLayout';
import { useAuth,HO_ROLES } from '../lib/auth';
const money=(v:number)=>'₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0});
function Kpi({label,value,note,icon:Icon,tone='text-honey-700'}:any){return <div className="card p-4"><div className="flex items-start justify-between"><div><div className="text-[10px] font-extrabold uppercase tracking-wide text-stone-500">{label}</div><div className="mt-1 font-heading text-2xl font-extrabold">{value}</div><div className="mt-1 text-[11px] font-semibold text-stone-500">{note}</div></div><Icon className={`h-5 w-5 ${tone}`}/></div></div>}
function Bars({rows,valueKey,labelKey,format=(x:any)=>x}:any){const max=Math.max(1,...rows.map((x:any)=>Number(x[valueKey])));return <div className="space-y-2">{rows.map((x:any)=><div key={x[labelKey]}><div className="mb-1 flex justify-between text-[11px] font-bold"><span>{String(x[labelKey]).replace(/_/g,' ')}</span><span>{format(x[valueKey])}</span></div><div className="h-2 rounded-full bg-stone-100"><div className="h-2 rounded-full bg-gradient-to-r from-amber-400 to-honey-600" style={{width:`${Math.max(2,Number(x[valueKey])/max*100)}%`}}/></div></div>)}</div>}
export default function Analytics(){const{user}=useAuth();const[unitId,setUnitId]=useState('');const[months,setMonths]=useState('6');const{data:units=[]}=useQuery({queryKey:['units'],queryFn:()=>api('/units'),enabled:!!user&&(HO_ROLES.includes(user.role)||user.role==='HR_MANAGER')});const qs=new URLSearchParams({months,...(unitId?{unitId}:{})});const{data:d,isLoading}=useQuery({queryKey:['analytics',unitId,months],queryFn:()=>api(`/analytics?${qs}`)});if(isLoading||!d)return <div><PageHeader title="Analytics" subtitle="Loading management intelligence…"/><div className="card p-12 text-center">Loading analytics…</div></div>;const k=d.kpis;return <div><PageHeader title="Analytics" subtitle={`Cross-module operational intelligence · generated ${new Date(d.generatedAt).toLocaleString('en-IN')}`}/><div className="card mb-4 flex flex-wrap gap-3 p-4">{units.length>0&&<select className="input max-w-xs" value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">All units</option>{units.map((u:any)=><option key={u.id} value={u.id}>{u.code} · {u.name}</option>)}</select>}<select className="input max-w-48" value={months} onChange={e=>setMonths(e.target.value)}><option value="3">Last 3 months</option><option value="6">Last 6 months</option><option value="12">Last 12 months</option></select></div>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Active students" value={k.students} note={`${k.leads} inquiries · ${k.conversion}% conversion`} icon={Users}/><Kpi label="Attendance" value={`${k.attendanceRate}%`} note="Present across selected period" icon={Activity} tone="text-emerald-600"/><Kpi label="Fee collection" value={money(k.feesCollected)} note={`${k.feeCollectionRate}% of ${money(k.feeTarget)}`} icon={IndianRupee}/><Kpi label="Payroll cost" value={money(k.payrollCost)} note="Net + employer contributions" icon={WalletCards} tone="text-violet-600"/><Kpi label="Inventory" value={money(k.inventoryValue)} note={`${k.lowStock} SKU(s) need reorder`} icon={Boxes}/><Kpi label="PTM attendance" value={`${k.ptmAttendance}%`} note="Recorded parent attendance" icon={Users}/><Kpi label="Evening centre" value={k.eveningStudents} note={`${money(k.eveningCollected)} collected`} icon={TrendingUp}/><Kpi label="Evening outstanding" value={money(k.eveningOutstanding)} note="Separate activity ledger" icon={IndianRupee} tone="text-rose-600"/></div>
<div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="card p-5"><h3 className="mb-4 font-heading font-extrabold">Admissions funnel</h3><Bars rows={d.funnel} valueKey="count" labelKey="stage"/></div><div className="card p-5"><h3 className="mb-4 font-heading font-extrabold">Academic planning</h3><Bars rows={Object.entries(d.academic).map(([status,count])=>({status,count}))} valueKey="count" labelKey="status"/></div><div className="card p-5 lg:col-span-2"><h3 className="mb-4 font-heading font-extrabold">Monthly financial trend</h3><div className="grid gap-4 sm:grid-cols-3">{d.trend.map((x:any)=><div key={x.month} className="rounded-xl bg-white/60 p-3"><b>{new Date(`${x.month}-01`).toLocaleDateString('en-IN',{month:'short',year:'2-digit'})}</b><div className="mt-2 text-xs text-stone-500">Fees <strong className="float-right text-emerald-700">{money(x.fees)}</strong></div><div className="mt-1 text-xs text-stone-500">Payroll <strong className="float-right text-violet-700">{money(x.payroll)}</strong></div><div className="mt-1 text-xs text-stone-500">Leads <strong className="float-right">{x.leads}</strong></div></div>)}</div></div></div></div>}
