import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { api,fmtDate } from '../lib/api';
import { PageHeader } from '../components/layout/AppLayout';
import { Modal,Field,ErrorNote } from '../components/ui/Modal';
import { Plus,ShieldAlert } from 'lucide-react';
const defaults:any={title:'',eventDate:new Date().toISOString().slice(0,10),status:'ACTIVE',details:''};
export default function Lifecycle(){const qc=useQueryClient();const [studentId,setStudentId]=useState('');const [tab,setTab]=useState('STUDENT_INFORMATION');const [open,setOpen]=useState(false);const [form,setForm]=useState(defaults);const [err,setErr]=useState('');
 const {data:tabs=[]}=useQuery({queryKey:['life-tabs'],queryFn:()=>api('/lifecycle/tabs')}); const {data:students=[]}=useQuery({queryKey:['life-students'],queryFn:()=>api('/lifecycle/students')}); const sid=studentId||students[0]?.id||'';
 const {data:rows=[]}=useQuery({queryKey:['life',sid,tab],queryFn:()=>api(`/lifecycle/student/${sid}?tab=${tab}`),enabled:!!sid});
 const save=useMutation({mutationFn:()=>api(`/lifecycle/student/${sid}`,{method:'POST',body:JSON.stringify({tab,title:form.title,eventDate:form.eventDate,status:form.status,payload:{details:form.details}})}),onSuccess:()=>{qc.invalidateQueries({queryKey:['life',sid,tab]});setOpen(false);setForm(defaults)},onError:(e:any)=>setErr(e.message)});
 const active=tabs.find((x:any)=>x.id===tab); return <div><PageHeader title="Student Lifecycle" subtitle="Complete 18-tab profile · visibility rules enforced by the API" action={<button className="btn-primary" disabled={!sid} onClick={()=>{setErr('');setOpen(true)}}><Plus className="mr-1 inline h-4 w-4"/>Add record</button>}/>
 <div className="card mb-4 p-4"><Field label="Student"><select className="input" value={sid} onChange={e=>setStudentId(e.target.value)}>{students.map((s:any)=><option key={s.id} value={s.id}>{s.firstName} {s.lastName} · {s.admissionNo}</option>)}</select></Field><div className="mt-3 flex gap-2 overflow-x-auto pb-2">{tabs.map((t:any)=><button key={t.id} onClick={()=>setTab(t.id)} className={tab===t.id?'btn-primary whitespace-nowrap':'btn-neo whitespace-nowrap'}>{t.label}{t.visibility!=='STAFF_PARENT'&&<ShieldAlert className="ml-1 inline h-3 w-3"/>}</button>)}</div></div>
 <div className="card p-5"><h3 className="font-heading font-extrabold">{active?.label}</h3><p className="mb-4 text-[11px] font-semibold text-stone-500">Visibility: {active?.visibility?.replace('_',' ')}</p>{!rows.length&&<div className="py-10 text-center text-sm font-semibold text-stone-400">No records in this tab.</div>}<div className="space-y-2">{rows.map((r:any)=><div key={r.id} className="rounded-xl bg-white/60 p-3"><div className="flex justify-between"><b className="text-[13px]">{r.title}</b><span className="text-[10px] text-stone-400">{fmtDate(r.eventDate||r.createdAt)}</span></div><p className="mt-1 whitespace-pre-wrap text-[12px] font-semibold text-stone-600">{r.payload?.details||'—'}</p><span className="chip mt-2">{r.status||'RECORDED'}</span></div>)}</div></div>
 {open&&<Modal title={`Add · ${active?.label}`} onClose={()=>setOpen(false)}>{err&&<ErrorNote msg={err}/>}<div className="space-y-3"><Field label="Title *"><input className="input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Date"><input type="date" className="input" value={form.eventDate} onChange={e=>setForm({...form,eventDate:e.target.value})}/></Field><Field label="Details"><textarea className="input min-h-28" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></Field></div><button className="btn-primary mt-4 w-full" disabled={!form.title||save.isPending} onClick={()=>save.mutate()}>Save record</button></Modal>}</div>}
